package com.desolatetimelines.acct.common.utils;

import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.List;
import java.util.stream.IntStream;
import java.util.stream.StreamSupport;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

public class SynchronizedOverflowingIntSequenceTest {

    @Test
    public void synchronizedOverflowingIntSequence_works_singleThread() {
        // Initialize the sequence
        final SynchronizedOverflowingIntSequence sequence =
            new SynchronizedOverflowingIntSequence(-100, 100, 10, true);

        // Create a list to hold the integers generated by the sequence
        final List<Integer> generatedIntegers = new ArrayList<>(20);

        // Use the sequence to generate the integers and put them in the list
        for (int i = 0; i < 21; i++) {
            generatedIntegers.add(sequence.incrementAndGet());
        }

        // The list should contain the expected integers in the expected order
        assertEquals(21, generatedIntegers.size());
        assertEquals(-100, generatedIntegers.get(0));
        assertEquals(100, generatedIntegers.get(20));

        // Make the sequence overflow
        final int overflowValue = sequence.incrementAndGet();

        // The sequence should have jumped back to the lower bound
        assertEquals(-100, overflowValue);
    }

    @Test
    public void synchronizedOverflowingIntSequence_works_multiThread() {
        // Initialize the sequence
        final SynchronizedOverflowingIntSequence sequence =
            new SynchronizedOverflowingIntSequence(-100, 100, 10, true);

        // Create a list to hold the distinct integers generated by the sequence
        final List<Integer> generatedIntegers =
            StreamSupport.stream(IntStream.rangeClosed(0, 20).spliterator(), true)
                .map(i -> sequence.incrementAndGet())
                .distinct()
                .toList();

        // The list should contain the expected number of unique integers
        assertEquals(21, generatedIntegers.size());
    }

    @Test
    public void synchronizedOverflowingIntSequence_overflowException() {
        // Initialize the sequence
        final SynchronizedOverflowingIntSequence sequence =
            new SynchronizedOverflowingIntSequence(0, 1, 1, false);

        // Get the values in the sequence
        assertEquals(0, sequence.incrementAndGet());
        assertEquals(1, sequence.incrementAndGet());

        // The next call should overflow the sequence and, since overflow is not allowed for this sequence,
        // overflowing should result in an exception
        assertThrows(IllegalStateException.class, sequence::incrementAndGet);
    }

}
