<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.desolatetimelines</groupId>
        <artifactId>acct</artifactId>
        <version>2.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>acct-currency-collector-framework</artifactId>
    <name>acct-currency-collector-framework</name>
    <description>Account management - Currency - Collector - Framework</description>

    <packaging>jar</packaging>

    <dependencies>
        <dependency>
            <groupId>com.desolatetimelines</groupId>
            <artifactId>acct-currency-collector-spec</artifactId>
            <version>${project.parent.version}</version>
        </dependency>

        <dependency>
            <groupId>com.desolatetimelines</groupId>
            <artifactId>acct-currency-collector-ro-bnr</artifactId>
            <version>${project.parent.version}</version>
        </dependency>
        <dependency>
            <groupId>com.desolatetimelines</groupId>
            <artifactId>acct-currency-collector-ro-bcr</artifactId>
            <version>${project.parent.version}</version>
        </dependency>
        <dependency>
            <groupId>com.desolatetimelines</groupId>
            <artifactId>acct-currency-collector-ro-bt</artifactId>
            <version>${project.parent.version}</version>
        </dependency>

        <dependency>
            <groupId>com.desolatetimelines</groupId>
            <artifactId>acct-currency-data</artifactId>
            <version>${project.parent.version}</version>
        </dependency>

        <dependency>
            <groupId>com.desolatetimelines</groupId>
            <artifactId>acct-catalog-ws-client</artifactId>
            <version>${project.parent.version}</version>
        </dependency>

        <dependency>
            <groupId>com.desolatetimelines</groupId>
            <artifactId>acct-currency-repo-memory</artifactId>
            <version>${project.parent.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.desolatetimelines</groupId>
            <artifactId>acct-catalog-ws-memory</artifactId>
            <version>${project.parent.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>joda-time</groupId>
            <artifactId>joda-time</artifactId>
            <version>2.3</version>
            <scope>compile</scope>
        </dependency>
    </dependencies>

</project>
