networks:
  primary:
    ipam:
      config:
        - subnet: 10.0.10.0/24

x-db-common-config: &dbCommonConfig
  image: postgres:${DOCKER_POSTGRES_IMAGE_VERSION}
  restart: always
  profiles:
    - everything
    - databases
  networks:
    - primary
  deploy:
    mode: replicated
    replicas: 1

x-service-common-config: &serviceCommonConfig
  restart: always
  networks:
    - primary
  env_file:
    - _environment.txt
    - _environment.containers.txt
  deploy:
    mode: replicated
    replicas: 1

x-service-boilerplate-config: &serviceBoilerplateConfig
  <<: *serviceCommonConfig
  profiles:
    - everything
    - application
    - boilerplate

x-service-acct-boilerplate-config: &serviceAcctBoilerplateConfig
  <<: *serviceCommonConfig
  profiles:
    - everything
    - application
    - boilerplate
    - acct-boilerplate

x-service-acct-service-config: &serviceAcctServiceConfig
  <<: *serviceCommonConfig
  profiles:
    - everything
    - application
    - boilerplate
    - acct-service

services:
  user-management-postgres:
    #container_name: acct-user-management-postgres
    # https://hub.docker.com/_/postgres
    <<: *dbCommonConfig
    hostname: user-management-postgres
    ports:
      - ${USER_MANAGEMENT_DB_PORT}:5432
    volumes:
      - ./data/user_management:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${USER_MANAGEMENT_DB_PASSWORD}
      - POSTGRES_USER=${USER_MANAGEMENT_DB_USERNAME}
      - POSTGRES_DB=${USER_MANAGEMENT_DB_NAME}

  security-postgres:
    <<: *dbCommonConfig
    hostname: security-postgres
    ports:
      - ${SECURITY_DB_PORT}:5432
    volumes:
      - ./data/security:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${SECURITY_DB_PASSWORD}
      - POSTGRES_USER=${SECURITY_DB_USERNAME}
      - POSTGRES_DB=${SECURITY_DB_NAME}

  usage-postgres:
    <<: *dbCommonConfig
    hostname: usage-postgres
    ports:
      - ${USAGE_DB_PORT}:5432
    volumes:
      - ./data/usage:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${USAGE_DB_PASSWORD}
      - POSTGRES_USER=${USAGE_DB_USERNAME}
      - POSTGRES_DB=${USAGE_DB_NAME}

  jobs-postgres:
    <<: *dbCommonConfig
    hostname: jobs-postgres
    ports:
      - ${JOBS_REGISTRY_DB_PORT}:5432
    volumes:
      - ./data/jobs:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${JOBS_REGISTRY_DB_PASSWORD}
      - POSTGRES_USER=${JOBS_REGISTRY_DB_USERNAME}
      - POSTGRES_DB=${JOBS_REGISTRY_DB_NAME}

  workspace-postgres:
    <<: *dbCommonConfig
    hostname: workspace-postgres
    ports:
      - ${WORKSPACE_DB_PORT}:5432
    volumes:
      - ./data/workspace:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${WORKSPACE_DB_PASSWORD}
      - POSTGRES_USER=${WORKSPACE_DB_USERNAME}
      - POSTGRES_DB=${WORKSPACE_DB_NAME}

  catalog-postgres:
    <<: *dbCommonConfig
    hostname: catalog-postgres
    ports:
      - ${CATALOG_DB_PORT}:5432
    volumes:
      - ./data/catalog:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${CATALOG_DB_PASSWORD}
      - POSTGRES_USER=${CATALOG_DB_USERNAME}
      - POSTGRES_DB=${CATALOG_DB_NAME}

  currency-postgres:
    <<: *dbCommonConfig
    hostname: currency-postgres
    ports:
      - ${CURRENCY_DB_PORT}:5432
    volumes:
      - ./data/currency:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${CURRENCY_DB_PASSWORD}
      - POSTGRES_USER=${CURRENCY_DB_USERNAME}
      - POSTGRES_DB=${CURRENCY_DB_NAME}

  reporting-postgres:
    <<: *dbCommonConfig
    hostname: reporting-postgres
    ports:
      - ${REPORTING_DB_PORT}:5432
    volumes:
      - ./data/reporting:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${REPORTING_DB_PASSWORD}
      - POSTGRES_USER=${REPORTING_DB_USERNAME}
      - POSTGRES_DB=${REPORTING_DB_NAME}

  eureka-service:
    <<: *serviceBoilerplateConfig
    build:
      context: ../
      dockerfile: containers/generic-app.docker
      args:
        - ACCT_VERSION=${ACCT_VERSION}
        - ACCT_MODULE_NAME=acct-eureka-server
        - DOCKER_ECLIPSE_TEMURIN_IMAGE_VERSION=${DOCKER_ECLIPSE_TEMURIN_IMAGE_VERSION}
    image: acct-eureka-server:${ACCT_VERSION}
    hostname: eureka-service
    ports:
      - ${EUREKA_SERVER_PORT}:${EUREKA_SERVER_PORT}

  authorization-service:
    <<: *serviceBoilerplateConfig
    build:
      context: ../
      dockerfile: containers/generic-app.docker
      args:
        - ACCT_VERSION=${ACCT_VERSION}
        - ACCT_MODULE_NAME=acct-authorization-server
        - DOCKER_ECLIPSE_TEMURIN_IMAGE_VERSION=${DOCKER_ECLIPSE_TEMURIN_IMAGE_VERSION}
    image: acct-authorization-server:${ACCT_VERSION}
    hostname: authorization-service
    ports:
      - ${AUTHORIZATION_SERVER_PORT}:${AUTHORIZATION_SERVER_PORT}
    depends_on:
      - eureka-service

  usage-service:
    <<: *serviceAcctBoilerplateConfig
    build:
      context: ../
      dockerfile: containers/generic-app.docker
      args:
        - ACCT_VERSION=${ACCT_VERSION}
        - ACCT_MODULE_NAME=acct-usage-ws-server
        - DOCKER_ECLIPSE_TEMURIN_IMAGE_VERSION=${DOCKER_ECLIPSE_TEMURIN_IMAGE_VERSION}
    image: acct-usage-ws-server:${ACCT_VERSION}
    hostname: usage-service
    ports:
      - ${USAGE_SERVER_PORT}:${USAGE_SERVER_PORT}
    depends_on:
      - eureka-service
      - usage-postgres
    links:
      - usage-postgres

  jobs-service:
    <<: *serviceAcctBoilerplateConfig
    build:
      context: ../
      dockerfile: containers/generic-app.docker
      args:
        - ACCT_VERSION=${ACCT_VERSION}
        - ACCT_MODULE_NAME=acct-job-ws-server
        - DOCKER_ECLIPSE_TEMURIN_IMAGE_VERSION=${DOCKER_ECLIPSE_TEMURIN_IMAGE_VERSION}
    image: acct-job-ws-server:${ACCT_VERSION}
    hostname: job-service
    ports:
      - ${JOBS_REGISTRY_SERVER_PORT}:${JOBS_REGISTRY_SERVER_PORT}
    depends_on:
      - eureka-service
      - jobs-postgres
    links:
      - jobs-postgres

  security-service:
    <<: *serviceAcctBoilerplateConfig
    build:
      context: ../
      dockerfile: containers/generic-app.docker
      args:
        - ACCT_VERSION=${ACCT_VERSION}
        - ACCT_MODULE_NAME=acct-security-ws-server
        - DOCKER_ECLIPSE_TEMURIN_IMAGE_VERSION=${DOCKER_ECLIPSE_TEMURIN_IMAGE_VERSION}
    image: acct-security-ws-server:${ACCT_VERSION}
    hostname: security-service
    ports:
      - ${SECURITY_SERVER_PORT}:${SECURITY_SERVER_PORT}
    depends_on:
      - eureka-service
      - usage-service
      - jobs-service
      - security-postgres
    links:
      - security-postgres

  user-management-service:
    <<: *serviceAcctBoilerplateConfig
    build:
      context: ../
      dockerfile: containers/generic-app.docker
      args:
        - ACCT_VERSION=${ACCT_VERSION}
        - ACCT_MODULE_NAME=acct-user-management-ws-server
        - DOCKER_ECLIPSE_TEMURIN_IMAGE_VERSION=${DOCKER_ECLIPSE_TEMURIN_IMAGE_VERSION}
    image: acct-user-management-ws-server:${ACCT_VERSION}
    hostname: user-management-service
    ports:
      - ${USER_MANAGEMENT_SERVER_PORT}:${USER_MANAGEMENT_SERVER_PORT}
    depends_on:
      - eureka-service
      - jobs-service
      - usage-service
      - user-management-postgres
    links:
      - user-management-postgres

  workspace-service:
    <<: *serviceAcctServiceConfig
    build:
      context: ../
      dockerfile: containers/generic-app.docker
      args:
        - ACCT_VERSION=${ACCT_VERSION}
        - ACCT_MODULE_NAME=acct-workspace-ws-server
        - DOCKER_ECLIPSE_TEMURIN_IMAGE_VERSION=${DOCKER_ECLIPSE_TEMURIN_IMAGE_VERSION}
    image: acct-workspace-ws-server:${ACCT_VERSION}
    hostname: workspace-service
    ports:
      - ${WORKSPACE_SERVER_PORT}:${WORKSPACE_SERVER_PORT}
    depends_on:
      - eureka-service
      - authorization-service
      - usage-service
      - jobs-service
      - workspace-postgres
    links:
      - workspace-postgres

  catalog-service:
    <<: *serviceAcctServiceConfig
    build:
      context: ../
      dockerfile: containers/generic-app.docker
      args:
        - ACCT_VERSION=${ACCT_VERSION}
        - ACCT_MODULE_NAME=acct-catalog-ws-server
        - DOCKER_ECLIPSE_TEMURIN_IMAGE_VERSION=${DOCKER_ECLIPSE_TEMURIN_IMAGE_VERSION}
    image: acct-catalog-ws-server:${ACCT_VERSION}
    hostname: catalog-service
    ports:
      - ${CATALOG_SERVER_PORT}:${CATALOG_SERVER_PORT}
    depends_on:
      - eureka-service
      - authorization-service
      - usage-service
      - jobs-service
      - catalog-postgres
    links:
      - catalog-postgres

  currency-service:
    <<: *serviceAcctServiceConfig
    build:
      context: ../
      dockerfile: containers/generic-app.docker
      args:
        - ACCT_VERSION=${ACCT_VERSION}
        - ACCT_MODULE_NAME=acct-currency-ws-server
        - DOCKER_ECLIPSE_TEMURIN_IMAGE_VERSION=${DOCKER_ECLIPSE_TEMURIN_IMAGE_VERSION}
    image: acct-currency-ws-server:${ACCT_VERSION}
    hostname: currency-service
    ports:
      - ${CURRENCY_SERVER_PORT}:${CURRENCY_SERVER_PORT}
    depends_on:
      - eureka-service
      - authorization-service
      - usage-service
      - jobs-service
      - currency-postgres
    links:
      - currency-postgres

  reporting-service:
    <<: *serviceAcctServiceConfig
    build:
      context: ../
      dockerfile: containers/generic-app.docker
      args:
        - ACCT_VERSION=${ACCT_VERSION}
        - ACCT_MODULE_NAME=acct-reporting-ws-server
        - DOCKER_ECLIPSE_TEMURIN_IMAGE_VERSION=${DOCKER_ECLIPSE_TEMURIN_IMAGE_VERSION}
    image: acct-reporting-ws-server:${ACCT_VERSION}
    hostname: reporting-service
    ports:
      - ${REPORTING_SERVER_PORT}:${REPORTING_SERVER_PORT}
    depends_on:
      - eureka-service
      - authorization-service
      - usage-service
      - jobs-service
      - reporting-postgres
    links:
      - reporting-postgres