version: '3.9'

networks:
  primary:
    ipam:
      config:
        - subnet: 10.0.10.0/24

services:
  user-management-postgres:
    #container_name: acct-user-management-postgres
    # https://hub.docker.com/_/postgres
    image: postgres:${DOCKER_POSTGRES_IMAGE_VERSION}
    restart: always
    profiles:
      - everything
      - databases
    networks:
      - primary
    ports:
      - ${USER_MANAGEMENT_DB_PORT}:5432
    volumes:
      - ./data/user_management:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${USER_MANAGEMENT_DB_PASSWORD}
      - POSTGRES_USER=${USER_MANAGEMENT_DB_USERNAME}
      - POSTGRES_DB=${USER_MANAGEMENT_DB_NAME}
    deploy:
      mode: replicated
      replicas: 1

  security-postgres:
    image: postgres:${DOCKER_POSTGRES_IMAGE_VERSION}
    restart: always
    profiles:
      - everything
      - databases
    networks:
      - primary
    ports:
      - ${SECURITY_DB_PORT}:5432
    volumes:
      - ./data/security:/var/lib/postgresql/data
#   env_files:
#     - 1.txt
#     - 2.txt
    environment:
      - POSTGRES_PASSWORD=${SECURITY_DB_PASSWORD}
      - POSTGRES_USER=${SECURITY_DB_USERNAME}
      - POSTGRES_DB=${SECURITY_DB_NAME}
    deploy:
      mode: replicated
      replicas: 1
#   depends_on:
#     - db

  usage-postgres:
    image: postgres:${DOCKER_POSTGRES_IMAGE_VERSION}
    restart: always
    profiles:
      - everything
      - databases
    networks:
      - primary
    ports:
      - ${USAGE_DB_PORT}:5432
    volumes:
      - ./data/usage:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${USAGE_DB_PASSWORD}
      - POSTGRES_USER=${USAGE_DB_USERNAME}
      - POSTGRES_DB=${USAGE_DB_NAME}
    deploy:
      mode: replicated
      replicas: 1

  jobs-postgres:
    image: postgres:${DOCKER_POSTGRES_IMAGE_VERSION}
    restart: always
    profiles:
      - everything
      - databases
    networks:
      - primary
    ports:
      - ${JOBS_REGISTRY_DB_PORT}:5432
    volumes:
      - ./data/jobs:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${JOBS_REGISTRY_DB_PASSWORD}
      - POSTGRES_USER=${JOBS_REGISTRY_DB_USERNAME}
      - POSTGRES_DB=${JOBS_REGISTRY_DB_NAME}
    deploy:
      mode: replicated
      replicas: 1